version: "3"

services:
  apache:
    container_name: apache
    image: httpd:latest
    ports:
      - 80:80
    volumes:
      - ./apache/apache.conf:/usr/local/apache2/conf/httpd.conf

  apache-exporter:
    container_name: apache-exporter
    image: lusotycoon/apache-exporter
    command: ["--scrape_uri", "http://apache/server-status/?auto"]
    depends_on:
      - apache
    
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - apache-exporter

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboard/default.yaml
      - ./grafana/dashboard.json:/var/lib/grafana/dashboards/apache.json
    depends_on:
      - prometheus